### ISSUE TITLE
Proper list of files/ORF's in index page

### ISSUE THREAD

**Issue by ilectra** [UCL/HHyeast-server#14]
The current drop-down is huge and unmanageable. Create either a search or (preferably) an alphabetically ordered list of links.

Since we're at it, add functionality to download file.

**Comment by tamuri** [comment]
Does WTForms have some kind of progressive search box that fills using Websockets?

**Comment by jonc125** [comment]
If people open the drop-down then start typing, their browser will search for them for entries starting with those characters. But most users probably don't know that :)
