### ISSUE TITLE
Fix bug with "detail" buttons

### ISSUE THREAD

**Issue by ilectra** [UCL/HHyeast-server#15]
In the summary page, there's a button for a detail page per database (3 in total), but they all redirect to `<blabla-url>/pdb`.

**Comment by jonc125** [comment]
You can avoid using forms entirely for this. Just define 3 button-style links in the template file, e.g.
```
<a class="btn" href="{{ url_for('load_detail', filename=name, db='pdb') }}">Detailed PDB hits</a>
```
