### ISSUE TITLE
Description text on the summary view is missing?

### ISSUE THREAD

**Issue by jonc125** [UCL/HHyeast-server#18]
Can't double-check this now, but the tooltip hovers on the summary plots seemed to be missing real labels.

**Comment by ilectra** [comment]
Well, these are the clustered hits, and I'm not quite sure what information we'd like to show there (that's not already on the plot).@timlevine ?

**Comment by ilectra** [comment]
In cluster view, "match No:" should be "cluster" and "description" should be: "Top hit of cluster:" and then the full info for the highest prob hit of the cluster.
