### ISSUE TITLE
Sort out Azure stuff

### ISSUE THREAD

**Issue by ilectra** [UCL/HHyeast-server#38]
Get Tim an Azure subscription and move server to it... 😫 
Might be able to do it with Terraform, see #4 .

**Comment by ilectra** [comment]
Good news! We can keep hhyeast-server in RSDG's Azure subscription for another year or so, covering up to £50/month. @timlevine , do you think you could come up with some funds to pitch in a bit, through an interdeprtmental transfer to us? (no Azure will be involved with this, we'll keep managing the subscription)

**Comment by timlevine** [comment]
could you explain what this means a bit more. RSDG? what the price will be after this?

T

________________________________

**Comment by ilectra** [comment]
RSDG is our group - Research Software Development Group. The server currently costs about £50/month, and we can in principle cover this from our budget for another year or so. I'm just asking if you could contribute a bit to decrease the cost for us, so that we can absorb any future changes in cost or who-knows-what. It would also show to the higher-ups that there is interest from the research community for a cloud hosting service provided by ISD/RITS, so that we can continue offering such hosting. It's entirely up to you, as I said, we can cover the whole cost if you don't have any funds available.

**Comment by jonc125** [comment]
@ilectra I think hosting costs should have come out of the original grant. In practice we used that to cover staff costs instead, so we should cover the hosting costs from our budget. But for CloudLabs politics we can still use this as an example of interest from the research community using grant money for cloud hosting, since that was written into the grant proposal.

**Comment by ilectra** [comment]
Ok then, that's fixed, we'll cover all server costs for a year or so. I just need to scale down this machine, I discovered it's not on sale anymore... 😟

**Comment by timlevine** [comment]
will the speed change?

T

________________________________

**Comment by tamuri** [comment]
Can we document the deploy process to the Azure installation please? Login URLs, usernames, passwords, paths, starting/stopping server etc. We can add a page on the wiki (https://github.com/UCL/HHyeast-server/wiki)

**Comment by ilectra** [comment]
The Azure server is `hhyeast.ukwest.cloudapp.azure.com`, for now I'm the only user (`ilektra`). The process (like, 4 commands) to start it from ssh is in the README.

I've setup uptimerobot to email me if the server is down. I also setup a service to re-start the hhyeast-server whenever the machine is restarted (see wiki and #56 ). This is our ultimate failsafe: if the server is down for some reason and I'm not around to ssh to it and fix it, any one of us (RSDG) can log in to the Azure portal and re-start the VM (hhserver297vm in the hhserver297rg resource group), and the hhyeast-server will be started at boot time as well.That being said, we should add at least one more person to the uptimerobot notifications. @tamuri ?

I also added google analytics to the website (linked to my personal account for now, but maybe we could make a group one), so after we go really public we can monitor traffic and performance.

**Comment by jonc125** [comment]
Yeah, it'd be good to have a group analytics account. I'll add it to my list :)

**Comment by tamuri** [comment]
Yes, add me.
