### ISSUE TITLE
error messages with different ORFs

### ISSUE THREAD

**Issue by timlevine** [UCL/HHyeast-server#50]
The few issues I've found in the past few weeks + insights from today!

http://hhyeast.ukwest.cloudapp.azure.com:5000/YJR039W
error msg: 'NoneType' object is not subscriptable

YMR103C: YMR103C is not a valid ORF. Please choose a different one.

Also: SMC = YJL074C: list index out of range. 
    For this, Asif worked out the the re are lots of very short (1 column) hits in Pfam, which gets the "list index out of range" error, which then also means that the same error is applied to the summary page

**Comment by ilectra** [comment]
YJR039W: fixed by #52 .
YMR103C: don't have the data, will review when uploading new stuff.
YJL074C: works now....

**Comment by ilectra** [comment]
KEL1, BNI1, YDR124w: fixed by #52 .
