### ISSUE TITLE
site completely stuck

### ISSUE THREAD

**Issue by timlevine** [UCL/HHyeast-server#65]
Hi Ilektra and Asif,
I am at conference where I have got quite a bit of interest in HHyeast. As I showed it to people I found it was stuck. Is there something going on whereby it has become overloaded? Another (non-exclusive) alternative is that somehow it crashed
Hope this is the right way to let you know this
All the best,
Tim

Friday May 24, 13:12

**Comment by ilectra** [comment]
Hello! I restarted the server, not quite sure what brought it down. It seems some `IndexError: list index out of range` errors kill the server, and some don't. I need to make some time to investigate this... I hope this didn't screw up your demos too much.
We have an automatic tool that emails us whenever the server is down, but do let us know as well if it's urgent to restart it (like eg. when you're showing it at a conference).

**Comment by timlevine** [comment]
Thanks for the info. I think that this crash did dent people's enthusiasm - it was just the day after we showed how good it was that people started asking me why it was not working. I then raised the issue on Github
T
