### ISSUE TITLE
cut-off for short hits (low "aligned cols" values) in HHyeast

### ISSUE THREAD

**Issue by timlevine** [UCL/HHyeast-server#66]
Hi Ilektra,
I just was looking at Pet130/YJL023C, when I noticed that the hits displayed at http://hhyeast.ucl.ac.uk:5000/PET130 have 22 and 23 aligned columns. The hits are highly informative, so I'm glad that they are there.

After seeing this, I am now confused about the minimum cut-off for length, which I remember being 30 columns. Could you remind me how you applied the length cut-off?
All the best,
Tim

**Comment by ilectra** [comment]
Hello, Tim
The cutoff is 30 columns if there are other hits that have above 30 columns. If there are not (like the case here), then hits with 20-30 columns are kept as well. See end of discussion in #9 . Does this still work for you?

**Comment by timlevine** [comment]
Yes  - sorry I didn't see this reply earlier! Seems I need to get better notifications!
