### ISSUE TITLE
Changes to 2D plot of hits

### ISSUE THREAD

**Issue by timlevine** [UCL/HHyeast-server#7]
The 2D plot of hits (x axis = start, y axis = lenght (or end) just does not work as the longest hits are so spearated from othe x-axis that most people will just not see them. The lenght of a hit must be shown by having a long line from hit start to hit end in the graphic, i.e. the graphic should not be a 2D graph, but a piled up version of a "1D graph" - just a rectangle for the length of the protein and the bars representing the hits all piled in virtually on top of each other (if there are several of a certain length then have a number above to indicate the maximum number of hits at any point - **see diagram attached**)
![possible graphing of hits option](https://user-images.githubusercontent.com/13528088/32674056-8b8945f2-c649-11e7-9392-defc99b40b77.jpg)

We didnt get time to talk about this today, so I thought it reasonable to park it here.

**Comment by tamuri** [comment]
We need to discuss this in front of a screen and a paper/pen. It won’t look as nice as the diagram above because there are, in general, a lot of overlapping domains.

**Comment by ilectra** [comment]
Get rid of the 2D plot once new clustering algorithm is (starting to get) implemented.
