### ISSUE TITLE
Fix naming of yeast database entries

### ISSUE THREAD

**Issue by ilectra** [UCL/HHyeast-server#8]
Function is done, only need to resolve the few proteins that only have a long description.

- [x] Send list to @timlevine

**Comment by tamuri** [comment]
“standard name” (VPS13) and “systematic name” (YLL040C)

**Comment by ilectra** [comment]
@timlevine apparently more than half the entries of Saccharomyces_cerevisiae_S288c.fas don't have a standard or a systematic name - see list in attachment. Should I be looking at a different file?

[yeast_wo_proper_name.txt](https://github.com/UCL/HHyeast-server/files/1548488/yeast_wo_proper_name.txt)

**Comment by tamuri** [comment]
One place to get the mapping could be [SGD DB cross-reference](https://downloads.yeastgenome.org/curation/chromosomal_feature/dbxref.tab)

You can pull out what you need using:
```
cut -d'    ' -f4,6 dbxref.tab | sort | uniq | grep '^Y’
```

**Comment by timlevine** [comment]
I am confused what we are missing here. Do we have to deal with the issue of proteins named NP_xxxxxx or has that been addressed?

**Comment by timlevine** [comment]
The SGD DB cross-reference file has lots of lists - maybe including the NP_xxxxxx ones too (I did not check yet). Among the 6611 entries with "UniProtKB UniProtKB/Swiss-Prot ID" 1468 have no given name, but many (?over half) of those are dubious ORFs that ewe are not interested in.

**Comment by ilectra** [comment]
Sorry for the confusion, there were 2 different issues we were trying to solve: 
1. Standard-systematic name correspondence
2. NP_xxxxxx names not having any standard or systematic name corresponding to them

Looking more closely at the cross-reference file, it seems all the information we need for both issues is there (6077 entries). I fished it out in file [yeast_names_ref.txt](https://github.com/UCL/HHyeast-server/files/1551165/yeast_names_ref.txt) . If it looks sane to you, I'll use that for naming cross-reference.

**Comment by timlevine** [comment]
that looks fine. it would be worth talking briefly about all the other things going on with the server sometime. I am mainly away this week, so possibly that could be done next week (not 18th, but I'm free after then). If that's not possible, then in the new year!
Tim

**Comment by ilectra** [comment]
@timlevine It seems the 6077 entries I mentioned earlier are not the complete set of proteins. If I search the cross-reference file for names starting with "Y", I get 6716 entries, and if I search for lines with "UniProtKB" in them, I get 6716.

What's the best set to use, and is there a way to get a complete one (i.e. any legitimate protein will be in that set)?

Other than that, the mechanics of dealing with the different name conventions are done I think (under review...).

**Comment by timlevine** [comment]
Many of the 6716 are names given to ORFs that have since been found to be NOT orfs - now labelled as "dubious ORFs"


nb I'm answering from my email not from GitHub - could you reply to say that you got this!


________________________________

**Comment by ilectra** [comment]
Yep, I got this! Will check tomorrow, gotta run!

________________________________

**Comment by ilectra** [comment]
[ Sorry, the entries with UniProtKB were 6732 ]

@timlevine So what should we do? Filter the "dubious ORFs" out? (how?) Or ignore anything outside the 6077 entries with NP_xxxx names? Or ... ?

**Comment by ilectra** [comment]
Only accept and show in the drop-down proteins in the list of 6077.
